anHsudo: required
language: node_js
dist: focal
node_js:
  - "16"
before_install:
  - sudo dpkg --add-architecture i386
  - sudo apt-get update -qq
  - sudo apt-get install -qq wine fakeroot xvfb python3.10 python3-pip python3-setuptools
  - sudo python3 -m pip install mkdocs-material
install: npm install
before_deploy:
deploy:
  provider: releases
  api-key:
    secure: Nb4qJlmLEE2/ETHEYe8V8eGI08d4GuE5kdQef5ZnB4PrstppLlAjShv5E4DNTsyalMOMDjpw9v+9aQNzxGiGv+lCVVL5oFvqvDpcYusRuF9Qua7oJtFh+5FvjgC1DDjauk5Z7WQWMvzWwfNmqbY/lxPbA4zVy4kdYkGV/8WnzA9AL5fU0ZU8gDsFjcr9Pz81XDsDXtPH/+iMuclMsEl8V/ZuswWlZaFn1Jnb1tcGC5WUCsuNQo/+gGfSK6Qcf9AKsIrOjdzi55s4jqH1N7P/kKi4a2tWUTwmSLrOxdUmSYjXVOxMu0cAEnHSeYREv/5o6J0MbfQrDoxh2y5roPZzqE+FAuFLl+b/+bYlW0mrfYfSuP/VX9LYh5JSvrhN7rZuUfMqS1iM7c9Dx8sZadMnvYEAAJhH8IV/9SkuRa/8QoIpXf7YB9v1jERxs4gk5CPT5Aml6nY/CvMWiEQ/wJhC7iZd/QRHshgfNLfAGlbbNU2KP6ZsVAGD601fyST/8neoQqLqS9mteOr1QME3c5EFw+XaauIQNYZSl+wJr8Y1YMcKY+fbJqqR0TXkbsoxFgV9PRf/4ZCjIJYtmelQVlM7j20XavOHM/Ko6/y7a3pohFz+ql3YR9jGF5XW2foXb4+e6DwTGL91/f75hYcsvXxoKbeaBjWpaSK8532UTeVkhPM=
  file_glob: true
  file: dist/packages/*
  skip_cleanup: true
  on:
    tags: true
before_deploy:
  - export VERSION=$(sed -nE 's/^\s*"version":\ "(.*?)",$/\1/p' package.json)
  - npm run build-docs
  - npm run package -- --all
  - npm run package-node
  - cd $TRAVIS_BUILD_DIR/dist/open-stage-control-linux-x64/resources/app/server/
  - wget https://github.com/jean-emmanuel/open-stage-control-midi/releases/latest/download/osc-midi-linux && chmod +x osc-midi-linux && echo "true" > osc-midi.json
  - cd $TRAVIS_BUILD_DIR/dist/open-stage-control-win32-x64/resources/app/server/
  - wget https://github.com/jean-emmanuel/open-stage-control-midi/releases/latest/download/osc-midi-windows.exe && chmod +x osc-midi-windows.exe && echo "true" > osc-midi.json
  - cd $TRAVIS_BUILD_DIR/dist/open-stage-control-darwin-x64/open-stage-control.app/Contents/Resources/app/server
  - wget https://github.com/jean-emmanuel/open-stage-control-midi/releases/latest/download/osc-midi-osx && chmod +x osc-midi-osx && echo "true" > osc-midi.json
  - cd $TRAVIS_BUILD_DIR
  - npm run deb64
  - cd dist
  - mkdir packages
  - mv open-stage-control-linux-x64/*.deb packages/open-stage-control-${VERSION}-amd64.deb
  - mv open-stage-control-node   open-stage-control-${VERSION}-node
  - mv open-stage-control-win32-x64    open-stage-control-${VERSION}-win32-x64
  - mv open-stage-control-linux-x64    open-stage-control-${VERSION}-linux-x64
  - zip -q -r --symlinks packages/open-stage-control-${VERSION}-osx.zip open-stage-control-darwin-x64/open-stage-control.app
  - zip -q -r packages/open-stage-control-${VERSION}-node.zip     open-stage-control-${VERSION}-node
  - zip -q -r packages/open-stage-control-${VERSION}-win32-x64.zip      open-stage-control-${VERSION}-win32-x64
  - zip -q -r packages/open-stage-control-${VERSION}-linux-x64.zip      open-stage-control-${VERSION}-linux-x64
  - ls packages
  - cd ..
