anHsudo: required
language: node_js
dist: focal
node_js:
  - "16"
before_install:
  - sudo dpkg --add-architecture i386
  - sudo apt-get update -qq
  - sudo apt-get install -qq wine fakeroot xvfb python3.10 python3-pip python3-setuptools rpm
  - python3 -m pip install mkdocs
  - python3 -m pip install mkdocs-material
install: npm install
before_deploy:
deploy:
  provider: releases
  api-key: $API_KEY
  file_glob: true
  file: dist/packages/*
  skip_cleanup: true
  on:
    tags: true
before_deploy:
  - yes | gem update --system --force
  - gem install bundler
  - gem install faraday-net_http -v '3.3.0'
  - gem install uri
  - gem install logger
  - export VERSION=$(sed -nE 's/^\s*"version":\ "(.*?)",$/\1/p' package.json)
  - npm run build-docs
  - npm run package -- --all
  - npm run package-node
  - cd $TRAVIS_BUILD_DIR/dist/open-stage-control-linux-x64/resources/app/server/
  - wget https://github.com/jean-emmanuel/open-stage-control-midi/releases/latest/download/osc-midi-linux && chmod +x osc-midi-linux && echo "true" > osc-midi.json
  - cd $TRAVIS_BUILD_DIR/dist/open-stage-control-win32-x64/resources/app/server/
  - wget https://github.com/jean-emmanuel/open-stage-control-midi/releases/latest/download/osc-midi-windows.exe && chmod +x osc-midi-windows.exe && echo "true" > osc-midi.json
  - cd $TRAVIS_BUILD_DIR/dist/open-stage-control-darwin-x64/open-stage-control.app/Contents/Resources/app/server
  - wget https://github.com/jean-emmanuel/open-stage-control-midi/releases/latest/download/osc-midi-osx && chmod +x osc-midi-osx && echo "true" > osc-midi.json
  # - cd $TRAVIS_BUILD_DIR/dist/open-stage-control-darwin-arm64/open-stage-control.app/Contents/Resources/app/server
  # - wget https://github.com/jean-emmanuel/open-stage-control-midi/releases/latest/download/osc-midi-osx && chmod +x osc-midi-osx && echo "true" > osc-midi.json
  - cd $TRAVIS_BUILD_DIR
  - mkdir dist/packages
  - npm run deb64
  - mv dist/open-stage-control-linux-x64/*.deb dist/packages/
  - npm run rpm64
  - cd dist
  - mv open-stage-control-node   open-stage-control_${VERSION}_node
  - mv open-stage-control-win32-x64    open-stage-control_${VERSION}_win32-x64
  - mv open-stage-control-linux-x64/*.rpm packages/
  - mv open-stage-control-linux-x64    open-stage-control_${VERSION}_linux-x64
  - zip -q -r --symlinks packages/open-stage-control_${VERSION}_osx-x64.zip open-stage-control-darwin-x64/open-stage-control.app
  - zip -q -r --symlinks packages/open-stage-control_${VERSION}_osx-arm64.zip open-stage-control-darwin-arm64/open-stage-control.app
  - zip -q -r packages/open-stage-control_${VERSION}_node.zip     open-stage-control_${VERSION}_node
  - zip -q -r packages/open-stage-control_${VERSION}_win32-x64.zip      open-stage-control_${VERSION}_win32-x64
  - zip -q -r packages/open-stage-control_${VERSION}_linux-x64.zip      open-stage-control_${VERSION}_linux-x64
  - ls packages
  - cd ..
